### ISSUE TITLE
Not Detecting Obvious Anomalies

### ISSUE THREAD

**Issue by xKHUNx** [nachonavarro/seasonal-esd-anomaly-detection#2]
So I've tried the code:
I've manually added 3 anomalies data points, run it with the settings below, using data set from here:
[https://anomaly.io/wp-content/uploads/download/webTraffic.csv](url)
```
traffic.loc['11/20/13'] = 200
traffic.loc['3/1/14'] = 200
traffic.loc['6/7/15'] = 200

outliers_indices = sesd.seasonal_esd(traffic['Visitors'], hybrid=False, max_anomalies=10, alpha=0.05, seasonality=30)
```

But the output I get is this:
Anomaly index: 0, anomaly date: 11/20/13, anomaly value: 200
Anomaly index: 100, anomaly date: 2/28/14, anomaly value: 54
Anomaly index: 562, anomaly date: 6/5/15, anomaly value: 125

This is weird because it does detect the first anomaly correctly, the rest are detected off by 1 or 2 position from the real anomaly.

I've tried run it with the original R implementation and gets a good result, with all 3 anomalies detected, I've tried debugging and comes to the conclusion that something might be off at the calculation of the residuals, I've plotted the decomposition plot and see the original residual plot are capable of detecting the anomalies. But when I try parsing:
"outliers = esd(**residual**, max_anomalies=max_anomalies, alpha=alpha)" with the residual I get from the residual plot, it doesn't works either.

**Comment by vlurgio** [comment]
Just ran into this as well. Seems the indices aren't being recalculated correctly  after the largest values are taken out

**Comment by nachonavarro** [comment]
I believe I've fixed the bug you guys are having. 

When performing `np.argmax(zscores)`, the elements removed via `ts = np.delete(ts, test_idx)` were not being taken into consideration, so potentially each time the anomaly index was being shifted by one, two, etc.

For example, if `ts = [1, 1, 1, 100, 1, 50, 1, 1]`, then on the first iteration we remove 100 which has index 3. Until here all fine. Then, `ts` becomes `ts = [1, 1, 1, 1, 50, 1, 1]`, and we remove 50, with index 4. But not really, as 50 has index 5 on the **original** time series and index 4 on the updated time series.

I've removed the part where I delete elements from the time series and now I just keep the original time series all the time. However, we still need to ignore the outliers each time we recalculate the zscores, so I have a mask that ignores those values.

If you could pull and check if this solves the problem and get back to me, I'll close the issue.

**Comment by nachonavarro** [comment]
I've checked the traffic example and it does seem to work:

```
import pandas as pd
import seasonal_esd as sesd

traffic = pd.read_csv('webTraffic.csv')
traffic.index = traffic.Date
traffic.at['11/20/13', 'Visite'] = 200
traffic.at['3/1/14', 'Visite'] = 200
traffic.at['6/7/15', 'Visite'] = 200
outliers_indices = sesd.seasonal_esd(traffic['Visite'], hybrid=False, max_anomalies=10, alpha=0.05, seasonality=30)
for idx in outliers_indices:
  print(traffic.iloc[idx])

>>> Date      11/20/13
>>> Visite         200
>>> Name: 11/20/13, dtype: object
>>> Date      3/1/14
>>> Visite       200
>>> Name: 3/1/14, dtype: object
>>> Date      6/7/15
>>> Visite       200
>>> Name: 6/7/15, dtype: object
```

**Comment by xKHUNx** [comment]
I've tested it as well, and it works. You can close the issue now.
