### ISSUE TITLE
Calculation of z-score for S-H-ESD

### ISSUE THREAD

**Issue by jason-osajima** [nachonavarro/seasonal-esd-anomaly-detection#3]
Thanks for putting this together! 

One quick comment: I noticed that the paper actually doesn't replace median with MAD when calculating the residual for the hybrid version.  Instead, they keep the residual the same but use the median and MAD instead of mean and SD when conducting the ESD test.

**Comment by nachonavarro** [comment]
Hi Jason! You're quite right, luckily if I understood correctly it's a quick fix. Checkout my changes to `sesd.py` and when you come back to me I'll close the issue.
