### ISSUE TITLE
Inaccurate description of decomposition

### ISSUE THREAD

**Issue by zdgriffith** [nachonavarro/seasonal-esd-anomaly-detection#4]
In the README: 

>  To circumvent this, STL decomposition is used.

However, the `seasonal_decompose` method from `statsmodels`  is used currently which doesn't include LOESS.  There is an STL implementation that was merged a few weeks ago that could be added as an option:  https://github.com/statsmodels/statsmodels/pull/5926

**Comment by nachonavarro** [comment]
Hey @zdgriffith nice finding, would you mind fixing it and submitting a pull request? I can't work on it at the moment!

**Comment by SwathyKrishnan29** [comment]
> In the README:
> 
> > To circumvent this, STL decomposition is used.
> 
> However, the `seasonal_decompose` method from `statsmodels` is used currently which doesn't include LOESS. There is an STL implementation that was merged a few weeks ago that could be added as an option: [statsmodels/statsmodels#5926](https://github.com/statsmodels/statsmodels/pull/5926)

Hi I am unable to use the STL function of statsmodels even after updating the package what to do?

**Comment by nachonavarro** [comment]
I've changed dependencies and now I'm using this implementation [](https://github.com/jrmontag/STLDecompose) which **does** include LOESS.
