### ISSUE TITLE
UserWarning: Warning partition will ignore the mask of the MaskedArray

### ISSUE THREAD

**Issue by batuhanaman** [nachonavarro/seasonal-esd-anomaly-detection#5]
Hi,

Thanks for the implementation. I am using this library for one of my projects. However, when I run the codes I get the following warning and the result is not correct. Am I missing something? Please let me know.

```
venv/lib/python3.5/site-packages/numpy/core/fromnumeric.py:745: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
```

Thanks.

**Comment by nachonavarro** [comment]
Fixed. See update
