### ISSUE TITLE
Package import error

### ISSUE THREAD

**Issue by rng1995** [nachonavarro/seasonal-esd-anomaly-detection#7]
Hi,

I am getting import error when I import stldecompose package. Didn't find solutions in internet. Kindly help.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-52-2d98a708a8b4> in <module>
      1 import numpy as np
      2 import scipy.stats as stats
----> 3 from stldecompose import decompose

/usr/local/lib/python3.7/site-packages/stldecompose/__init__.py in <module>
----> 1 from .stl import decompose, forecast

/usr/local/lib/python3.7/site-packages/stldecompose/stl.py in <module>
      3 from pandas.core.nanops import nanmean as pd_nanmean
      4 from statsmodels.tsa.seasonal import DecomposeResult
----> 5 from statsmodels.tsa.filters._utils import _maybe_get_pandas_wrapper_freq

ImportError: cannot import name '_maybe_get_pandas_wrapper_freq' from 'statsmodels.tsa.filters._utils' (/usr/local/lib/python3.7/site-packages/statsmodels/tsa/filters/_utils.py)

Thanks,
Naren

**Comment by rng1995** [comment]
from ._utils import _maybe_get_pandas_wrapper - This wrapper does not exist in utils function of statsmodels. Please update your code on that..Thanks!

**Comment by dxma** [comment]
> from ._utils import _maybe_get_pandas_wrapper - This wrapper does not exist in utils function of statsmodels. Please update your code on that..Thanks!

Hi, I was trying to use this package as well. It is the dependant package stldecompose which refers to an older version of statsmodels. 
The best way to get rid of this situation now is:
1. install sesd into a new virtual python environment;
2. rollback statsmodels to version 0.10.2 (other than the latest 0.11.1).

**Comment by nachonavarro** [comment]
Fixed. Update to sesd 0.2. Now we use the [STL class](https://www.statsmodels.org/stable/generated/statsmodels.tsa.seasonal.STL.html#statsmodels.tsa.seasonal.STL) in the statsmodels package. One dependency less!
