### ISSUE TITLE
package install error

### ISSUE THREAD

**Issue by xrzalreadytaken** [nachonavarro/seasonal-esd-anomaly-detection#8]
Hi,
I'm using pip to install the package, but I got the following error:
Looking in indexes: http://cmc-cd-mirror.rnd.huawei.com/pypi/simple/
Collecting sesd
  Downloading http://cmc-cd-mirror.rnd.huawei.com/pypi/packages/1f/f2/99c8c45daff97ba18cdbac7faec7e612be599c23a94012972dbdc1624264/sesd-0.1.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\z00484114\AppData\Local\Temp\pip-install-bgt1a_io\sesd\setup.py", line 4, in <module>
        long_description = f.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 977: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\z00484114\AppData\Local\Temp\pip-install-bgt1a_io\sesd\

Can anyon help? Thanks!

**Comment by dxma** [comment]
this can be addressed by setting PYTHONUTF8=1 before pip install. However this package is currently broken on a dependent package stldecompose.

**Comment by nachonavarro** [comment]
Fixed. Update to sesd 0.2. Now we use the [STL class](https://www.statsmodels.org/stable/generated/statsmodels.tsa.seasonal.STL.html#statsmodels.tsa.seasonal.STL) in the statsmodels package. One dependency less!
